jobs:
  build_dev_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/login-action@v2
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/elimity-com/insights-client-go:${{ github.run_id }}

on: workflow_dispatch
