jobs:
  arrange:
    container: ghcr.io/elimity-com/insights-client-go:6547437779
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: test -z "$(goarrange run -d -r)"

  lint:
    container: ghcr.io/elimity-com/insights-client-go:6547437779
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: GOFLAGS='-buildvcs=false' golangci-lint run

  test:
    container: ghcr.io/elimity-com/insights-client-go:6547437779
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go test -v ./...

  tidy:
    container: ghcr.io/elimity-com/insights-client-go:6547437779
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go mod tidy
      - run: |
          git -c safe.directory=/__w/insights-client-go/insights-client-go diff --quiet go.mod go.sum

on: pull_request
