jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.13'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.3
      - run: go test -v

on: pull_request
