jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35
      - run: go test -v

on: pull_request
